<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Google.GenAI" Version="1.21.0" />
	  <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
	  <PackageReference Include="pythonnet" Version="3.1.0" />
	  <PackageReference Include="System.IO.Ports" Version="10.0.11" />
	</ItemGroup>

	<!-- adb.exe ဲ့ fastboot.exe ကို Output folder ထဲ အလိုအလျောက် Copy ပေးမယ် -->
	<ItemGroup>
		<None Update="adb.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="fastboot.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="AdbWinApi.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="AdbWinUsbApi.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="mi.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>